esphome:
  name: ecoflow-espidf

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: "your-wifi"
  password: "your-password"

logger:
  baud_rate: 0

external_components:
  - source:
      type: local
      path: ../components
    components: [ef_ps]

# Try ESP-IDF framework to improve driver support for 1000kbps
canbus:
  - platform: esp32_can
    id: ecoflow_can
    can_id: 0x351
    tx_pin: GPIO5
    rx_pin: GPIO4
    bit_rate: 1000kbps

ef_ps:
  id: ecoflow_bridge
  canbus_id: ecoflow_can
  update_interval: 1s

interval:
  - interval: 1s
    then:
      - lambda: |-
          extern ::EcoflowConfig config;
          config.volt = 5120;
          config.soc = 75;
          config.temp = 25;
          config.canTxEnabled = true;
          ESP_LOGI("ef_espidf", "Test values set: V=%d SOC=%d T=%d", config.volt, config.soc, config.temp);

api: {}
